### ISSUE TITLE
Error on Checkout

### ISSUE THREAD

**Issue by pod3d** [PayUMEA/payu-mea-rpp-woocommerce#3]
Woocommerce: Version 2.6.1  
Wordpress: Version 4.5.2
Sandbox enabled

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by ryangodfreyza** [comment]
Hi pod3d

We see that this issue has been closed. 

Can you please advise how you have resolved this for future users?
